/* 연동 화면 «툴 카탈로그»·«연동 요청» 기본 문구(한국어). 호스트가 labels 로 덮는다. */
export const CATALOG_DEFAULT_LABELS = {
  tabs: { admin: '어드민 관리' },
  catalog: {
    title: '조직 활성화 툴 카탈로그',
    description: '어드민이 활성화한 툴만 구성원이 연동할 수 있습니다.',
    requiredOff: '필수 연동이 꺼져 있습니다 — 초대 발송·일정 연동이 동작하지 않습니다',
    columns: { tool: '툴', category: '카테고리', status: '상태', personal: '개인 연동 허용', action: '액션' },
    groups: {
      tool: { label: '작업 도구 (수집)', desc: '활동 데이터를 가져옵니다' },
      send: { label: '발송 채널', desc: '초대·알림·증명서를 보냅니다' },
      hr: { label: '인사 시스템', desc: '인사 데이터를 주고받습니다' },
    },
    active: '활성화',
    inactive: '비활성화',
    activate: '활성화',
    deactivate: '비활성화',
    companyOnly: '— 회사 단위 연결 (직원은 계정 잇기만)',
    companyChannel: '— 회사 채널 (해당 없음)',
    personalToggle: '{{name}} 개인 연동 허용',
    loading: '불러오는 중...',
    loadFailed: '툴 카탈로그를 불러오지 못했습니다.',
    retry: '다시 시도',
    confirmStatusTitle: '{{name}} 을(를) 비활성화할까요?',
    confirmStatusBody: '기존 연동 {{n}}건이 다음 만료 시점에 차단됩니다.',
    confirmStatusNote: '그 전까지는 수집이 계속되고, 만료 뒤에는 다시 연결할 수 없습니다.',
    confirmPersonalTitle: '{{name}} 개인 연동 허용을 끌까요?',
    confirmPersonalBody: '기존 개인 연동 {{n}}건이 다음 만료 시점에 차단됩니다.',
    confirmPersonalNote: '새 개인 연결은 지금부터 막히고, 다시 켜도 끊긴 연결은 자동으로 되살아나지 않습니다.',
    confirm: '확인',
    cancel: '취소',
  },
  requests: {
    title: '구성원 연동 요청',
    pending: '{{count}}건 대기',
    description: '지원되지 않는 툴 요청을 검토하고 우선순위를 결정합니다.',
    empty: '접수된 연동 요청이 없습니다.',
    loadFailed: '연동 요청을 불러오지 못했습니다.',
    status: { pending: '대기', reviewing: '검토 중', approved: '승인됨', rejected: '반려됨' },
    approve: '승인',
    reject: '반려',
  },
  inactiveTools: { title: '어드민 활성화 필요', badge: '어드민 활성화 필요' },
  requestBanner: {
    title: '원하는 툴이 없으신가요?',
    message: 'PIVIT에 연동 요청을 보내면 검토 후 활성화 가능 여부를 알림으로 회신드립니다.',
    button: 'PIVIT에 연동 요청',
  },
  requestModal: {
    title: 'PIVIT에 연동 요청',
    description: '현재 PIVIT이 지원하지 않는 협업툴을 요청하세요. 검토 후 활성화 가능 여부를 알림으로 회신드립니다.',
    toolName: '툴 이름',
    toolNamePlaceholder: '예: Asana, Trello, Figma',
    toolNameHint: '2자 이상',
    purpose: '사용 용도',
    purposePlaceholder: '어떤 데이터를 PIVIT에 연동하고 싶은지 적어주세요',
    purposeHint: '5자 이상',
    email: '요청자 이메일',
    submit: '요청 제출',
    submitting: '제출 중…',
    cancel: '취소',
    close: '닫기',
  },
  personalChips: {
    title: '개인 연동',
    inactive: '어드민 활성화 필요',
    blocked: '개인 연동 차단',
  },
};
