/* 따로 보관한 기록 칸의 문구 (PW-1429 · 퇴사 처리 정책서 v1.19 §3-C) */
/** 한국어 기본 문구 — 소비자가 `labels` 로 덮는다(영어 화면). */
export const ARCHIVED_RECORDS_DEFAULT_LABELS = {
  section: '따로 보관한 기록',
  badge: '법정 보존',
  intro: '퇴사가 확정되어 아래 기록을 다른 정보와 분리해 보관하고 있어요. 화면·검색·집계·AI·내보내기에는 쓰지 않습니다.',
  pending: '퇴사가 확정됐어요. 오늘 밤 아래 기록을 다른 정보와 분리해 보관합니다.',
  items: ['근로계약', '임금·보상 이력', '급여 계좌', '평가 최종 등급·승진 심의 결과', '인적 사항'],
  meta: '{retire} 퇴사 구간 · {moved} 옮김 · {purge} 파기 예정',
  metaPending: '{retire} 퇴사 구간 · 오늘 밤 옮김',
  download: '보관 기록 내려받기',
  confirmTitle: '{name} 님의 보관 기록을 파일로 받습니다',
  confirmBody: '감독기관 제출·분쟁 대응처럼 법령이 정한 목적에만 씁니다. 화면에는 펼치지 않고 CSV 파일로만 받습니다. 내려받은 사람·시각·사유는 아래 기록과 감사 로그에 남고 지울 수 없습니다.',
  reasonPlaceholder: '사유 (필수) — 예: 노동청 자료 제출 요구(공문 날짜)',
  cancel: '취소',
  confirm: '내려받기',
  downloading: '내려받는 중…',
  failed: '내려받지 못했습니다 — 다시 시도하세요',
  logTitle: '내려받은 기록',
  logEmpty: '아직 내려받은 사람이 없습니다.',
  loading: '따로 보관한 기록을 불러오는 중…',
  loadError: '따로 보관한 기록을 불러오지 못했습니다.',
  retry: '다시 시도',
  note: '퇴사가 확정되어 따로 보관 중입니다',
};
